spring:
  # change datasource before running
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update